FORMAT_TIPS = {
        'flights': {
            'flight departure time': "The answer format must be 'hh:mm' in 24-hour system, e.g., '13:44'.",
            'yes or no': "The answer must be 'Yes' or 'No'",
            'flight number': "The answer must be (a sequence of) numerical code(s), e.g., '1400', or '1383, 2201'.",
            'time difference': "The answer format must be a string representing an interge for minutes, e.g., '10'.",
            'delay of arrival time': "The answer format must be a string representing a floating-point number with one decimal place for minutes, e.g., '121.0'.",
            'extra minutes': "The answer format must be a a string representing a floating-point number with one decimal place for minutes, e.g., '-11.0'.",
            'local arrival time': "The answer format must be 'hh:mm' in 24-hour system, e.g., '13:44'.",
            'CRS-recorded arrival time': "The answer format must be 'hh:mm' in 24-hour system, e.g., '13:44'.",
            'flight duration': "The answer format must be a string representing an interge for minutes.",
            'minutes taking to taxi in': "The answer format must be a string representing an interge for minutes.",
            # for hard questions:
            'percentage': "The answer format must be a string representing a floating-point number with one decimal place, followed by a percentage sign, e,g,. '10.0%'.",
            'average delay time': "The answer format must be a string representing a floating-point number with one decimal place.",
            'diverted flights': "The answer format must be a string representing an integer.",
            'flights with long distance': "The answer format must be a string representing an integer.",
            'average airtime': "The answer format must be a string representing a floating-point number with one decimal place for minutes.",
            'flights from A to B': "The answer format must be a string representing an integer.",
            'average flight time': "The answer format must be a string representing a floating-point number with one decimal place for minutes.",
            "fastest flight": "The answer format must be a string representing a flight.",
            "average speed": "The answer format must be a string representing a floating-point number with one decimal place.",
            "total number": "The answer format must be a string representing an integer.",
        },
        'coffee':{
            "opening price": "The answer format must be a string representing price. Use the value you get from the database as the answer. You do not need to round the number.",
            "lowest price": "The answer format must be a string representing price. Use the value you get from the database as the answer. You do not need to round the number.",
            "highest price": "The answer format must be a string representing price. Use the value you get from the database as the answer. You do not need to round the number.",
            "closing price": "The answer format must be a string representing price. Use the value you get from the database as the answer. You do not need to round the number.",
            "volume": "The answer format must be a string representing an integer.",
            "percentage change": "The answer format must be a string representing a floating-point number with two decimal place, followed by a percentage sign.",
            "A or B": "The answer must be either 'bullish or 'bearish'.",
            "range of coffee price": "The answer format must be a string representing a floating-point number with two decimal place.",
            # for hard questions:
            'highest coffee price': "The answer format must be a string representing a floating-point. Use the value you get from the database as the answer. You do not need to round the number.",
            'lowest coffee price': "The answer format must be a string representing a floating-point. Use the value you get from the database as the answer. You do not need to round the number.",
            'average coffee price': "The answer format must be a string representing a floating-point number with one decimal place.",
            'coffee price change': "The answer format must be a string representing a floating-point number with one decimal place.",
            'percentage change comparison': "The answer format must be a string representing a floating-point number with one decimal place, followed by a percentage sign.",
            'day with the greatest price change': "The answer format must be a string representing a date in the format 'YYYY-MM-DD'.",
            'average daily volume': "The answer format must be a string representing a floating-point number with one decimal place.",
            'day with the highest increase': "The answer format must be a string representing a date in the format 'YYYY-MM-DD'.",
            'times of coffee price': "The answer format must be a string representing an integer.",
            'percentage increase': "The answer format must be a string representing a floating-point number with one decimal place, followed by a percentage sign.",
            'coffee price range': "The answer format must be a string representing a floating-point number with one decimal place.",
            'day with the higher close price': "The answer format must be a string representing an integer.",
            'average percentage change': "The answer format must be a string representing a floating-point number with one decimal place, followed by a percentage sign."

        },
        'airbnb': {
            "host's name": "The answer format must be a string representing a name.",
            "days available": "The answer format must be a string representing an interge for days, e.g., '10'.",
            "room type": "The answer format must be a string representing a room type.",
            "price": "The answer format must be a string representing an integer, prefixed with a dollar sign, e.g., '$1100'.",
            "minimum number of nights": "The answer format must be a string representing an integer, e.g., '2'.",
            "when constructed": "The answer format must be a string representing a year 'YYYY', e.g., '2019'.",
            "how many reviews": "The answer format must be a string representing an integer, e.g., '20'.",
            "last review date": "The answer format must be a string representing a date in the format 'month/day/year', e.g., '5/23/2018'. If the data is not available, please return 'null'.",
            "review rate number": "The answer format must be a string representing a floating-point number with one decimal place, e.g., '4.5'.",
            "average reviews per month": "The answer format must be a string representing a floating-point number. If the answer is not available, please return 'null'.",
            # for hard questions:
            'total price': "The answer format must be a string representing a floating-point number with one decimal place, prefixed with a dollar sign.",
            'how many airbnbs': "The answer format must be a string representing an integer.",
            'average price': "The answer format must be a string representing a floating-point number with one decimal place, prefixed with a dollar sign.",
            'average review rates': "The answer format must be a string representing a floating-point number with two decimal place.",
            'proporion of airbnbs': "The answer format must be a string representing a floating-point number with one decimal place, e.g., '0.3'.",
            'cost per night': "The answer format must be a string representing an integer, prefixed with a dollar sign, e.g., '$1100'.",
            'airbnb with high rate': "The answer format must be a string representing an integer.",
            'room with the lowest price': "The answer format must be a string representing a name.",
            'room with the highest review rate': "The answer format must be a string representing a name.",
            'shared room with the lowest price': "The answer format must be a string representing a name."
        },
        'yelp':{
            "address": "The answer format must be a string representing an address.",
            "city": "The answer format must be a string representing cities. If there are multiple cities, separate them with a comma and a space ', '.",
            "state": "The answer format must be a string representing a state.",
            "postal code": "The answer format must be a string representing a code.",
            "star rating": "The answer format must be a string representing a floating-point number with one decimal place for the star rating.",
            "how many reviews": "The answer format must be a string representing an integer.",
            "yes or no - openning": "The answer must be either 'Yes' or 'No'.",
            "yes or no - appointment": "The answer must be either 'Yes' or 'No'.",
            "hours of operation": "The answer format must be a string representing hours of operation.",
            "categories": "The answer format must be a string representing categories.",
            "coordinates": "The answer format must be a string representing coordinates.",
            # for hard questions:
            'how many business': "The answer format must be a string representing an integer.",
            'business in total': "The answer format must be a string representing an integer.",
            'highest star rating': "The answer format must be a string representing a name.",
            'highest review count': "The answer format must be a string representing a name.",
            'average review counts': "The answer format must be a string representing a floating-point number with two decimal place.",
            'nearest business': "The answer format must be a string representing a name.",
            'business recommendation': "The answer format must be a string representing a name.",
            'business not open': "The answer format must be a string representing an integer.",
            'average star rating': "The answer format must be a string representing a floating-point number with one decimal place.",
            'postal code region': "The answer format must be a string representing a code.",
        }
}
